FROM python:3.11-slim AS base

WORKDIR /work

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .
CMD ["streamlit","run","app/main.py","--server.port=8501","--server.address=0.0.0.0"]